codecov:
  allow_coverage_offsets: true

parsers:
  go:
    partials_as_hits: true

coverage:
  precision: 1
  range: "60...90"  # range are 60-90, see https://testing.googleblog.com/2020/08/code-coverage-best-practices.html
  round: down

  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: include

    project:
      default:
        target: auto
        threshold: 1.0
        if_not_found: success

    patch:
      default:
        target: 50%
        threshold: auto
        only_pulls: true
        if_not_found: failure

    changes:
      default:
        if_not_found: success
        only_pulls: true
        branches:
          - main

ignore:
  - "caller.go"

comment:
  layout: "newheader, diff, flags, files"
  behavior: default
  require_changes: false
  show_carryforward_flags: true
  hide_comment_details: false

github_checks:
  annotations: true
