name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true

      - name: Cache tools binaries
        id: go-tools-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/zap-cloudlogging/zap-cloudlogging/tools/bin
          key: go-tools-${{ runner.os }}-${{ hashFiles('tools/go.sum') }}
          restore-keys: go-tools-${{ runner.os }}-${{ hashFiles('tools/go.sum') }}

      - name: Take a coverage
        run: |
          make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: false
